# 행정동 코드로 변경

In [1]:
import pandas as pd
import numpy as np

1. 시군구 경계 전처리 파일(pd.read)

In [2]:
# sigungu_pro(시군구 경계 전처리) 파일 -> 팀원과 약속한 행정동 기준 지역코드로 통합하기 위한 파일 불러오기
df = pd.read_csv('../data/sigungu_pro.csv', encoding= 'cp949')
df

     fid  BASE_DATE  SIGUNGU_CD SIGUNGU_NM   지역코드
0      1   20240630       11060       동대문구  11230
1      2   20240630       11070        중랑구  11260
2      3   20240630       11080        성북구  11290
3      4   20240630       11090        강북구  11305
4      5   20240630       11100        도봉구  11320
..   ...        ...         ...        ...    ...
247  248   20240630       38580        함양군  48870
248  249   20240630       38590        거창군  48880
249  250   20240630       38600        합천군  48890
250  251   20240630       39010        제주시  50110
251  252   20240630       39020       서귀포시  50130

[252 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fid         252 non-null    int64
 1   BASE_DATE   252 non-null    int64
 2   SIGUNGU_CD  252 non-null    int64
 3   SIGUNGU_NM  252 non-null    object
 4   지역코드        252 non-null    int64
dtypes: int64(4), object(1)
memory usage: 10.0+ KB

In [4]:
# merge 시키기 위해 'SIGUNGU_CD'도 남겨두기
df=df[['SIGUNGU_CD','지역코드']]
df

     SIGUNGU_CD   지역코드
0         11060  11230
1         11070  11260
2         11080  11290
3         11090  11305
4         11100  11320
..          ...    ...
247       38580  48870
248       38590  48880
249       38600  48890
250       39010  50110
251       39020  50130

[252 rows x 2 columns]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SIGUNGU_CD  252 non-null    int64
 1   지역코드        252 non-null    int64
dtypes: int64(2)
memory usage: 4.1 KB

         SIGUNGU_CD          지역코드
count    252.000000    252.000000
mean   29883.476190  39152.055556
std     8092.330288  12124.853236
min    11010.000000  11110.000000
25%    24037.500000  29166.250000
50%    32065.000000  43435.000000
75%    36512.500000  47832.500000
max    39020.000000  52800.000000

---

2. 하천 규모 전처리 파일 (pd.read)

In [7]:
# river_pro 파일 
#   - RIV_DIS_MIN.csv 파일과 국가기본도_하천중심선_전처리.csv 파일 merge한 전처리 파일
#       - 깃허브에 올릴 때는 위 두 파일 없음. 전처리 결과 csv 파일만 올릴 예정. 폴더 효율성을 위함
#   - 하천 규모 5등급 -> 3등급으로 전처리도 함
#   - 즉, 하천 관련 정보는 다 있으나 시군구 코드 등 지역코드가 아직 통일이 안된 상태
riv_df=pd.read_csv('../data/river_pro.csv')
riv_df

     RIVER_SE  RIV_GRD  SIGUNGU_CD SIGUNGU_NM  RIV_DIS_MIN  RIV_DIS_GRD
0      RVC002        2       32610        양양군   478.260258            3
1      RVC002        2       32610        양양군   472.676208            3
2      RVC002        2       32610        양양군   464.709738            3
3      RVC002        2       32610        양양군   468.304507            3
4      RVC002        2       32610        양양군   297.178959            4
...       ...      ...         ...        ...          ...          ...
1462   RVC002        2       39010        제주시   229.527556            4
1463   RVC002        2       39010        제주시   345.132782            3
1464   RVC002        2       39010        제주시   452.014581            3
1465   RVC002        2       39010        제주시   525.988454            3
1466   RVC003        3       39010        제주시   467.574582            3

[1467 rows x 6 columns]

In [8]:
riv_df.info()
riv_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1467 entries, 0 to 1466
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RIVER_SE     1467 non-null   object
 1   RIV_GRD      1467 non-null   int64
 2   SIGUNGU_CD   1467 non-null   int64
 3   SIGUNGU_NM   1467 non-null   object
 4   RIV_DIS_MIN  1467 non-null   float64
 5   RIV_DIS_GRD  1467 non-null   int64
dtypes: float64(1), int64(3), object(2)
memory usage: 68.9+ KB

           RIV_GRD    SIGUNGU_CD   RIV_DIS_MIN  RIV_DIS_GRD
count  1467.000000   1467.000000   1467.000000  1467.000000
mean      2.738923  33947.657805   1137.008513     2.601227
std       0.448590   5386.918171   1715.864998     1.058880
min       1.000000  11020.000000     11.170640     1.000000
25%       2.000000  32070.000000    320.848563     2.000000
50%       3.000000  36020.000000    583.513990     3.000000
75%       3.000000  38050.000000   1146.709138     3.000000
max       3.000000  39020.000000  14313.919918     5.000000

---

# MERGE 2

In [9]:
merged_df = pd.merge(riv_df,df,on='SIGUNGU_CD',how='inner')

In [10]:
merged_df

     RIVER_SE  RIV_GRD  SIGUNGU_CD SIGUNGU_NM  RIV_DIS_MIN  RIV_DIS_GRD   지역코드
0      RVC002        2       32610        양양군   478.260258            3  51830
1      RVC002        2       32610        양양군   472.676208            3  51830
2      RVC002        2       32610        양양군   464.709738            3  51830
3      RVC002        2       32610        양양군   468.304507            3  51830
4      RVC002        2       32610        양양군   297.178959            4  51830
...       ...      ...         ...        ...          ...          ...    ...
1462   RVC002        2       39010        제주시   229.527556            4  50110
1463   RVC002        2       39010        제주시   345.132782            3  50110
1464   RVC002        2       39010        제주시   452.014581            3  50110
1465   RVC002        2       39010        제주시   525.988454            3  50110
1466   RVC003        3       39010        제주시   467.574582            3  50110

[1467 rows x 7 columns]

In [ ]:
# 필요 없는 컬럼 제외 
merged_df=merged_df.drop(columns=['RIVER_SE','SIGUNGU_CD','SIGUNGU_NM'])
merged_df

      RIV_GRD  RIV_DIS_MIN  RIV_DIS_GRD   지역코드
0           2   478.260258            3  51830
1           2   472.676208            3  51830
2           2   464.709738            3  51830
3           2   468.304507            3  51830
4           2   297.178959            4  51830
...       ...          ...          ...    ...
1462        2   229.527556            4  50110
1463        2   345.132782            3  50110
1464        2   452.014581            3  50110
1465        2   525.988454            3  50110
1466        3   467.574582            3  50110

[1467 rows x 4 columns]

In [ ]:
# 지역코드 컬럼명 변경 -> SIGUNGU
merged_df=merged_df.rename(columns={'지역코드': 'SIGUNGU'})
merged_df

      RIV_GRD  RIV_DIS_MIN  RIV_DIS_GRD  SIGUNGU
0           2   478.260258            3    51830
1           2   472.676208            3    51830
2           2   464.709738            3    51830
3           2   468.304507            3    51830
4           2   297.178959            4    51830
...       ...          ...          ...      ...
1462        2   229.527556            4    50110
1463        2   345.132782            3    50110
1464        2   452.014581            3    50110
1465        2   525.988454            3    50110
1466        3   467.574582            3    50110

[1467 rows x 4 columns]

---

# CSV 저장

In [14]:
riv_pro_df = merged_df.copy()

#  CSV 저장
riv_pro_df.to_csv("../data/riv_pro_df.csv", index=False, encoding="utf-8-sig")
print(" 저장 완료: ../data/riv_pro_df.csv")

 저장 완료: ../data/riv_pro_df.csv