# hello world

In [1]:
import pandas as pd
import numpy as np
import io

In [2]:
df_sido = pd.read_csv("./data/raw/sido.txt", 
                 header=None, 
                 names=['CTPRVN_CD', 'CTPRVN_NAME'], 
                 quotechar="'", 
                 skipinitialspace=True)
df_sido.head()

   CTPRVN_CD CTPRVN_NAME
0         11       서울특별시
1         26       부산광역시
2         27       대구광역시
3         28       인천광역시
4         29       광주광역시

In [3]:
df_sigungu = pd.read_csv("./data/raw/sigungu.txt", 
                 header=None, 
                 names=['SGG_CD', 'CTPRVN_CD', 'SGG_NAME'], 
                 quotechar="'", 
                 skipinitialspace=True)
df_sigungu.head()

   SGG_CD  CTPRVN_CD SGG_NAME
0   11000         11       전체
1   26000         26       전체
2   27000         27       전체
3   28000         28       전체
4   29000         29       전체

In [4]:
df_merged = pd.merge(df_sido, df_sigungu, on='CTPRVN_CD', how='inner')
df_merged['AREA_NAME'] = df_merged['CTPRVN_NAME'] + " " + df_merged['SGG_NAME'] 
df_merged.to_csv("./data/processed/area.csv", index=False)
df_merged.head(20)

    CTPRVN_CD CTPRVN_NAME  SGG_CD SGG_NAME   AREA_NAME
0          11       서울특별시   11000       전체    서울특별시 전체
1          11       서울특별시   11110      종로구   서울특별시 종로구
2          11       서울특별시   11140       중구    서울특별시 중구
3          11       서울특별시   11170      용산구   서울특별시 용산구
4          11       서울특별시   11200      성동구   서울특별시 성동구
5          11       서울특별시   11215      광진구   서울특별시 광진구
6          11       서울특별시   11230     동대문구  서울특별시 동대문구
7          11       서울특별시   11260      중랑구   서울특별시 중랑구
8          11       서울특별시   11290      성북구   서울특별시 성북구
9          11       서울특별시   11305      강북구   서울특별시 강북구
10         11       서울특별시   11320      도봉구   서울특별시 도봉구
11         11       서울특별시   11350      노원구   서울특별시 노원구
12         11       서울특별시   11380      은평구   서울특별시 은평구
13         11       서울특별시   11410     서대문구  서울특별시 서대문구
14         11       서울특별시   11440      마포구   서울특별시 마포구
15         11       서울특별시   11470      양천구   서울특별시 양천구
16         11       서울특별시   11500      강서구   서울특별시 강서구
17         11       서울특별시   11530      구로구   서울특별시 구로구
18         11       서울특별시   11545      금천구   서울특별시 금천구
19         11       서울특별시   11560     영등포구  서울특별시 영등포구