In [133]:
import pandas as pd

In [134]:
df_1 = pd.read_csv('./data/pump_all_data.csv', encoding='cp949')
# df_1 = df_1.filter(items=['시설명', '시도명', '시군구명', '위도', '경도', '제공기관코드', '제공기관명'])

df_1

,시설명,시도명,시군구명,소재지도로명주소,소재지지번주소,위도,경도,전화번호,설치년도,설치목적,데이터기준일자,제공기관코드,제공기관명
0,와룡배수장,경상북도,예천군,NaN,경상북도 예천군 풍양면 낙상리 1346-15,36.516146,128.271317,NaN,2009.0,재난대응,2025-12-17,5230000,경상북도 예천군
1,마전배수장,경상북도,예천군,NaN,경상북도 예천군 지보면 마전리 1247,36.525129,128.370952,NaN,2020.0,재난대응,2025-12-17,5230000,경상북도 예천군
2,무이배수장,경상북도,예천군,NaN,경상북도 문경시 영순면 달지리 1173,36.578642,128.294006,NaN,2012.0,재난대응,2025-12-17,5230000,경상북도 예천군
3,향석 배수장,경상북도,예천군,NaN,경상북도 예천군 용궁면 향석리 353-4,36.588135,128.300253,NaN,1999.0,재난대응,2025-12-17,5230000,경상북도 예천군
4,서정자 배수장,경상북도,예천군,NaN,경상북도 예천군 예천읍 상동리 73-1,36.629146,128.425687,NaN,2004.0,재난대응,2025-12-17,5230000,경상북도 예천군
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550,외토2 배수장,경상남도,합천군,NaN,경상남도 합천군 삼가면 외토리 1351-5,35.370697,128.081515,NaN,2022.0,침수방지,2025-07-23,5480000,경상남도 합천군
551,외토 배수장,경상남도,합천군,NaN,경상남도 합천군 삼가면 외토리 1218-1,35.369117,128.089468,NaN,2014.0,침수방지,2025-07-23,5480000,경상남도 합천군
552,오목마을 배수펌프장,경기도,의정부시,경기도 의정부시 용민로 105,경기도 의정부시 민락동 736-2,37.739750,127.089267,NaN,2001.0,내수배제,2025-06-24,3820000,경기도 의정부시
553,신흥마을 배수펌프장,경기도,의정부시,NaN,경기도 의정부시 의정부동 89-5,37.730346,127.047013,NaN,2008.0,내수배제,2025-06-24,3820000,경기도 의정부시
554,호원동 간이배수펌프장,경기도,의정부시,경기도 의정부시 안말로101번길 11,경기도 의정부시 호원동 446-44,37.714968,127.049877,NaN,2001.0,내수배제,2025-06-24,3820000,경기도 의정부시

In [135]:
# 예외 처리
df_1.loc[df_1['소재지지번주소'].str.contains('덕양구', na=False), '시군구명'] = '고양시 덕양구'
df_1.loc[df_1['소재지지번주소'].str.contains('일산서구', na=False), '시군구명'] = '고양시 일산서구'
df_1.loc[df_1['소재지지번주소'].str.contains('오정구', na=False), '시군구명'] = '부천시 오정구'
df_1.loc[df_1['소재지지번주소'].str.contains('소사구', na=False), '시군구명'] = '부천시 소사구'
df_1.loc[df_1['소재지지번주소'].str.contains('영통구', na=False), '시군구명'] = '수원시 영통구'
df_1.loc[df_1['소재지지번주소'].str.contains('권선구', na=False), '시군구명'] = '수원시 권선구'
df_1.loc[df_1['소재지지번주소'].str.contains('만안구', na=False), '시군구명'] = '안양시 만안구'
df_1.loc[df_1['소재지지번주소'].str.contains('동안구', na=False), '시군구명'] = '안양시 동안구'

df_1

,시설명,시도명,시군구명,소재지도로명주소,소재지지번주소,위도,경도,전화번호,설치년도,설치목적,데이터기준일자,제공기관코드,제공기관명
0,와룡배수장,경상북도,예천군,NaN,경상북도 예천군 풍양면 낙상리 1346-15,36.516146,128.271317,NaN,2009.0,재난대응,2025-12-17,5230000,경상북도 예천군
1,마전배수장,경상북도,예천군,NaN,경상북도 예천군 지보면 마전리 1247,36.525129,128.370952,NaN,2020.0,재난대응,2025-12-17,5230000,경상북도 예천군
2,무이배수장,경상북도,예천군,NaN,경상북도 문경시 영순면 달지리 1173,36.578642,128.294006,NaN,2012.0,재난대응,2025-12-17,5230000,경상북도 예천군
3,향석 배수장,경상북도,예천군,NaN,경상북도 예천군 용궁면 향석리 353-4,36.588135,128.300253,NaN,1999.0,재난대응,2025-12-17,5230000,경상북도 예천군
4,서정자 배수장,경상북도,예천군,NaN,경상북도 예천군 예천읍 상동리 73-1,36.629146,128.425687,NaN,2004.0,재난대응,2025-12-17,5230000,경상북도 예천군
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550,외토2 배수장,경상남도,합천군,NaN,경상남도 합천군 삼가면 외토리 1351-5,35.370697,128.081515,NaN,2022.0,침수방지,2025-07-23,5480000,경상남도 합천군
551,외토 배수장,경상남도,합천군,NaN,경상남도 합천군 삼가면 외토리 1218-1,35.369117,128.089468,NaN,2014.0,침수방지,2025-07-23,5480000,경상남도 합천군
552,오목마을 배수펌프장,경기도,의정부시,경기도 의정부시 용민로 105,경기도 의정부시 민락동 736-2,37.739750,127.089267,NaN,2001.0,내수배제,2025-06-24,3820000,경기도 의정부시
553,신흥마을 배수펌프장,경기도,의정부시,NaN,경기도 의정부시 의정부동 89-5,37.730346,127.047013,NaN,2008.0,내수배제,2025-06-24,3820000,경기도 의정부시
554,호원동 간이배수펌프장,경기도,의정부시,경기도 의정부시 안말로101번길 11,경기도 의정부시 호원동 446-44,37.714968,127.049877,NaN,2001.0,내수배제,2025-06-24,3820000,경기도 의정부시

In [136]:
df_1.info()
df_1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시설명       555 non-null    object
 1   시도명       555 non-null    object
 2   시군구명      555 non-null    object
 3   소재지도로명주소  267 non-null    object
 4   소재지지번주소   514 non-null    object
 5   위도        555 non-null    float64
 6   경도        555 non-null    float64
 7   전화번호      363 non-null    object
 8   설치년도      493 non-null    float64
 9   설치목적      555 non-null    object
 10  데이터기준일자   555 non-null    object
 11  제공기관코드    555 non-null    int64
 12  제공기관명     555 non-null    object
dtypes: float64(3), int64(1), object(9)
memory usage: 56.5+ KB

               위도          경도         설치년도        제공기관코드
count  555.000000  555.000000   493.000000  5.550000e+02
mean    36.165715  127.752526  2006.965517  4.423848e+06
std      1.080153    0.931085    10.842593  8.753361e+05
min     34.434055  126.260341  1968.000000  3.070000e+06
25%     35.210947  126.899383  2001.000000  3.630000e+06
50%     35.865703  127.478752  2008.000000  4.160000e+06
75%     37.413058  128.715709  2015.000000  5.330000e+06
max     38.089321  129.281953  2025.000000  6.270000e+06

In [137]:
df_1 = df_1.rename(columns = {'시도명': 'SIDO_N', '시군구명': 'SIGUNGU_N', '시설명': 'PUMP_CNT'})
df_1

,PUMP_CNT,SIDO_N,SIGUNGU_N,소재지도로명주소,소재지지번주소,위도,경도,전화번호,설치년도,설치목적,데이터기준일자,제공기관코드,제공기관명
0,와룡배수장,경상북도,예천군,NaN,경상북도 예천군 풍양면 낙상리 1346-15,36.516146,128.271317,NaN,2009.0,재난대응,2025-12-17,5230000,경상북도 예천군
1,마전배수장,경상북도,예천군,NaN,경상북도 예천군 지보면 마전리 1247,36.525129,128.370952,NaN,2020.0,재난대응,2025-12-17,5230000,경상북도 예천군
2,무이배수장,경상북도,예천군,NaN,경상북도 문경시 영순면 달지리 1173,36.578642,128.294006,NaN,2012.0,재난대응,2025-12-17,5230000,경상북도 예천군
3,향석 배수장,경상북도,예천군,NaN,경상북도 예천군 용궁면 향석리 353-4,36.588135,128.300253,NaN,1999.0,재난대응,2025-12-17,5230000,경상북도 예천군
4,서정자 배수장,경상북도,예천군,NaN,경상북도 예천군 예천읍 상동리 73-1,36.629146,128.425687,NaN,2004.0,재난대응,2025-12-17,5230000,경상북도 예천군
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550,외토2 배수장,경상남도,합천군,NaN,경상남도 합천군 삼가면 외토리 1351-5,35.370697,128.081515,NaN,2022.0,침수방지,2025-07-23,5480000,경상남도 합천군
551,외토 배수장,경상남도,합천군,NaN,경상남도 합천군 삼가면 외토리 1218-1,35.369117,128.089468,NaN,2014.0,침수방지,2025-07-23,5480000,경상남도 합천군
552,오목마을 배수펌프장,경기도,의정부시,경기도 의정부시 용민로 105,경기도 의정부시 민락동 736-2,37.739750,127.089267,NaN,2001.0,내수배제,2025-06-24,3820000,경기도 의정부시
553,신흥마을 배수펌프장,경기도,의정부시,NaN,경기도 의정부시 의정부동 89-5,37.730346,127.047013,NaN,2008.0,내수배제,2025-06-24,3820000,경기도 의정부시
554,호원동 간이배수펌프장,경기도,의정부시,경기도 의정부시 안말로101번길 11,경기도 의정부시 호원동 446-44,37.714968,127.049877,NaN,2001.0,내수배제,2025-06-24,3820000,경기도 의정부시

In [138]:
# 시도명, 시군구명으로 집계
groupby_df_1 = df_1.groupby(['SIDO_N', 'SIGUNGU_N'])
groupby_df_1.count()

                   PUMP_CNT  소재지도로명주소  소재지지번주소  위도  경도  전화번호  설치년도  설치목적  \
SIDO_N  SIGUNGU_N
강원특별자치도 강릉시               2         2        2   2   2     2     2     2
        동해시               1         0        1   1   1     1     1     1
경기도     가평군               2         2        2   2   2     0     2     2
        고양시 덕양구           5         5        5   5   5     5     5     5
        고양시 일산서구          3         3        3   3   3     3     3     3
...                     ...       ...      ...  ..  ..   ...   ...   ...
충청남도    논산시               7         7        7   7   7     7     7     7
        아산시               5         0        5   5   5     0     5     5
        홍성군               3         0        3   3   3     0     3     3
충청북도    단양군               1         1        0   1   1     1     1     1
        충주시               8         0        8   8   8     0     8     8

                   데이터기준일자  제공기관코드  제공기관명
SIDO_N  SIGUNGU_N
강원특별자치도 강릉시              2       2      2
        동해시              1       1      1
경기도     가평군              2       2      2
        고양시 덕양구          5       5      5
        고양시 일산서구         3       3      3
...                    ...     ...    ...
충청남도    논산시              7       7      7
        아산시              5       5      5
        홍성군              3       3      3
충청북도    단양군              1       1      1
        충주시              8       8      8

[82 rows x 11 columns]

In [139]:
# 필요한 컬럼 값만 남김
df_1 = groupby_df_1.count()
df_1 = df_1.filter(items=['SIDO_N', 'SIGUNGU_N', 'PUMP_CNT'])
df_1

                   PUMP_CNT
SIDO_N  SIGUNGU_N
강원특별자치도 강릉시               2
        동해시               1
경기도     가평군               2
        고양시 덕양구           5
        고양시 일산서구          3
...                     ...
충청남도    논산시               7
        아산시               5
        홍성군               3
충청북도    단양군               1
        충주시               8

[82 rows x 1 columns]

In [140]:
# 데이터 평면화
df_1 = df_1.reset_index()
df_1

     SIDO_N SIGUNGU_N  PUMP_CNT
0   강원특별자치도       강릉시         2
1   강원특별자치도       동해시         1
2       경기도       가평군         2
3       경기도   고양시 덕양구         5
4       경기도  고양시 일산서구         3
..      ...       ...       ...
77     충청남도       논산시         7
78     충청남도       아산시         5
79     충청남도       홍성군         3
80     충청북도       단양군         1
81     충청북도       충주시         8

[82 rows x 3 columns]

In [141]:
# 해당 DF에 지역코드 매칭을 위해 새로운 컬럼 생성
df_1['SIGUNGU_FNM'] = df_1['SIDO_N'] + ' ' + df_1['SIGUNGU_N'] 
df_1

     SIDO_N SIGUNGU_N  PUMP_CNT   SIGUNGU_FNM
0   강원특별자치도       강릉시         2   강원특별자치도 강릉시
1   강원특별자치도       동해시         1   강원특별자치도 동해시
2       경기도       가평군         2       경기도 가평군
3       경기도   고양시 덕양구         5   경기도 고양시 덕양구
4       경기도  고양시 일산서구         3  경기도 고양시 일산서구
..      ...       ...       ...           ...
77     충청남도       논산시         7      충청남도 논산시
78     충청남도       아산시         5      충청남도 아산시
79     충청남도       홍성군         3      충청남도 홍성군
80     충청북도       단양군         1      충청북도 단양군
81     충청북도       충주시         8      충청북도 충주시

[82 rows x 4 columns]

In [142]:
df_2 = pd.read_csv('./data/solid_data.csv', encoding='cp949')
df_2

,BASE_DATE,SIGUNGU_CD,SIGUNGU_NM,SIGUNGU_FNM,AREA,PERIMETER,CODE_DC,SOILDRA
0,20240630,11230,동대문구,서울특별시 동대문구,1.303090e+07,72698.6,4,약간불량
1,20240630,11260,중랑구,서울특별시 중랑구,3.189180e+07,189323.0,2,양호
2,20240630,11290,성북구,서울특별시 성북구,8.938390e+07,215908.0,1,매우양호
3,20240630,11305,강북구,서울특별시 강북구,8.938390e+07,215908.0,1,매우양호
4,20240630,11320,도봉구,서울특별시 도봉구,8.938390e+07,215908.0,1,매우양호
...,...,...,...,...,...,...,...,...
247,20240630,48870,함양군,경상남도 함양군,9.052580e+08,5197780.0,1,매우양호
248,20240630,48880,거창군,경상남도 거창군,8.108190e+08,4985870.0,1,매우양호
249,20240630,48890,합천군,경상남도 합천군,8.108190e+08,4985870.0,1,매우양호
250,20240630,50110,제주시,제주특별자치도 제주시,1.488240e+09,3370980.0,2,양호
251,20240630,50130,서귀포시,제주특별자치도 서귀포시,1.488240e+09,3370980.0,2,양호

In [143]:
all_data = pd.merge(df_1, df_2, on = 'SIGUNGU_FNM', how = 'left')

all_data

,SIDO_N,SIGUNGU_N,PUMP_CNT,SIGUNGU_FNM,BASE_DATE,SIGUNGU_CD,SIGUNGU_NM,AREA,PERIMETER,CODE_DC,SOILDRA
0,강원특별자치도,강릉시,2,강원특별자치도 강릉시,20240630,51150,강릉시,3.543320e+08,1058720.0,1,매우양호
1,강원특별자치도,동해시,1,강원특별자치도 동해시,20240630,51170,동해시,3.543320e+08,1058720.0,1,매우양호
2,경기도,가평군,2,경기도 가평군,20240630,41820,가평군,3.679320e+09,10497900.0,1,매우양호
3,경기도,고양시 덕양구,5,경기도 고양시 덕양구,20240630,41281,고양시 덕양구,8.595090e+07,771835.0,2,양호
4,경기도,고양시 일산서구,3,경기도 고양시 일산서구,20240630,41287,고양시 일산서구,5.650940e+07,252179.0,4,약간불량
...,...,...,...,...,...,...,...,...,...,...,...
77,충청남도,논산시,7,충청남도 논산시,20240630,44230,논산시,1.022210e+08,573461.0,4,약간불량
78,충청남도,아산시,5,충청남도 아산시,20240630,44200,아산시,7.963170e+07,742850.0,2,양호
79,충청남도,홍성군,3,충청남도 홍성군,20240630,44800,홍성군,5.324620e+07,389225.0,2,양호
80,충청북도,단양군,1,충청북도 단양군,20240630,43800,단양군,1.355650e+09,6899290.0,1,매우양호
81,충청북도,충주시,8,충청북도 충주시,20240630,43130,충주시,1.445190e+09,7288490.0,1,매우양호

In [144]:
all_data = all_data.filter(items=['SIGUNGU_CD', 'CODE_DC', 'PUMP_CNT'])
all_data = all_data.rename(columns = {'SIGUNGU_CD': 'SIGUNGU', 'CODE_DC': 'DRAINAGE_GRD'})
all_data

    SIGUNGU  DRAINAGE_GRD  PUMP_CNT
0     51150             1         2
1     51170             1         1
2     41820             1         2
3     41281             2         5
4     41287             4         3
..      ...           ...       ...
77    44230             4         7
78    44200             2         5
79    44800             2         3
80    43800             1         1
81    43130             1         8

[82 rows x 3 columns]