In [668]:
# # 공인 아이피 확인

# import requests, os
# from dotenv import load_dotenv, find_dotenv

# load_dotenv(find_dotenv())

# print("DISASTER_API loaded:", bool(os.getenv("DISASTER_API")))

# for u in ["https://api.ipify.org", "https://ifconfig.me/ip"]:
#     try:
#         print(u, requests.get(u, timeout=10).text.strip())
#     except Exception as e:
#         print(u, "fail:", e)

In [669]:
# import os
# import requests
# import pandas as pd
# from pathlib import Path
# from dotenv import load_dotenv

# load_dotenv()

# BASE_URL = "https://www.safetydata.go.kr/V2/api/DSSP-IF-00058"
# SERVICE_KEY = os.getenv("DISASTER_API")   # 너가 쓰던 env 변수명

# # ✅ (1) .py 파일에서 실행할 때(팀원 코드 방식)
# # PROJECT_ROOT = Path(__file__).resolve().parents[4]

# # ✅ (2) ipynb에서 실행할 때(추천)
# PROJECT_ROOT = Path.cwd()

# OUTPUT_PATH = PROJECT_ROOT / "data" / "raw" / "DSSP_IF_00058_all.csv"


# def _parse_response(payload: dict):
#     """
#     API 응답 JSON 파싱
#     - 정상 서비스여도 마지막 페이지 이후에는 body=None이 올 수 있음(너가 겪은 케이스)
#     """
#     items = payload.get("body")
#     total_cnt = payload.get("totalCount")

#     # 마지막 페이지 이후: body가 None이면 빈 리스트로 처리해서 정상 종료 유도
#     if items is None:
#         items = []

#     return items, total_cnt


# def fetch_data(page_no=1, num_of_rows=1000):
#     """
#     DSSP-IF-00058 한 페이지 수집

#     Returns:
#         tuple: (pd.DataFrame, total_count)
#     """
#     if not SERVICE_KEY:
#         raise ValueError("[CRAWL_00058] DISASTER_API 환경변수(.env) 설정 필요")

#     params = {
#         "serviceKey": SERVICE_KEY,
#         "returnType": "json",
#         "pageNo": page_no,
#         "numOfRows": num_of_rows,
#     }

#     try:
#         response = requests.get(BASE_URL, params=params, timeout=30)
#         response.raise_for_status()
#         payload = response.json()

#     except requests.exceptions.RequestException as e:
#         raise RuntimeError(f"[CRAWL_00058] API 호출 오류: {e}")
#     except ValueError as e:
#         raise RuntimeError(f"[CRAWL_00058] JSON 파싱 오류: {e}")

#     # ✅ 헤더 코드 체크 (에러면 여기서 바로 알려줌)
#     header = payload.get("header", {})
#     if str(header.get("resultCode")) not in ("00", "0", "None"):
#         raise RuntimeError(f"[CRAWL_00058] API Error {header.get('resultCode')}: {header.get('resultMsg')} / {header.get('errorMsg')}")

#     items, total_cnt = _parse_response(payload)

#     return pd.DataFrame(items), total_cnt


# def save_data(output_path=OUTPUT_PATH, max_rows=None):
#     """
#     DSSP-IF-00058 전체 수집 후 CSV 저장

#     Args:
#         output_path: 저장 경로
#         max_rows: 최대 수집 행 수 (None이면 전체)
#     """
#     path = Path(output_path)
#     path.parent.mkdir(parents=True, exist_ok=True)

#     print(f"[CRAWL_00058] 데이터 수집 시작: {path}")

#     ROWS_PER_PAGE = 1000

#     df_init, total_cnt = fetch_data(page_no=1, num_of_rows=ROWS_PER_PAGE)
#     all_dfs = [df_init]

#     if total_cnt is None:
#         # totalCount가 없으면 빈 페이지까지 while로 돌려야 하지만,
#         # 너가 본 응답엔 totalCount가 있었으니 보통 여기 안 탐.
#         print("[CRAWL_00058] totalCount가 없어 1페이지만 저장합니다.")
#     else:
#         print(f"[CRAWL_00058] 전체 데이터 수: {total_cnt}")

#         total_pages = (int(total_cnt) + ROWS_PER_PAGE - 1) // ROWS_PER_PAGE

#         for page_no in range(2, total_pages + 1):
#             try:
#                 df_page, _ = fetch_data(page_no=page_no, num_of_rows=ROWS_PER_PAGE)

#                 # ✅ 마지막 페이지 이후: body=None → df_page empty면 정상 종료
#                 if df_page.empty:
#                     break

#                 all_dfs.append(df_page)

#                 current_total = sum(len(d) for d in all_dfs)
#                 print(f"[CRAWL_00058] 페이지 {page_no}/{total_pages} 수집 완료 (누적: {current_total}개)")

#                 if max_rows and current_total >= max_rows:
#                     break

#             except Exception as e:
#                 raise RuntimeError(f"[CRAWL_00058] 페이지 {page_no} 수집 실패: {e}")

#     df_disaster = pd.concat(all_dfs, ignore_index=True)

#     if max_rows:
#         df_disaster = df_disaster.head(max_rows)

#     df_disaster.to_csv(path, index=False, encoding="utf-8-sig")
#     print(f"[CRAWL_00058] 데이터 수집 완료: {path} (총 {len(df_disaster)}건)")

#     return df_disaster


# if __name__ == "__main__":
#     save_data()

In [670]:
# df_disaster = save_data()
# df_disaster.head()

In [671]:
import numpy as np
import pandas as pd

df_disaster = pd.read_csv('../../../data/raw/DSSP_IF_00058_all.csv')
df_disaster.head()

,STDG_CD,CNTNC_VL,DST_RSK_DSTRCTCD,FCLTY_GRD_NM,DCSD_CNT,DST_RSK_DSTRCT_RGN_CD,DST_RSK_DSTRCT_HONU,ACT_LMT_MUOR_SPTR,ROAD_NM_CD,DSGN_AREA,...,APLY_YN,DADDR,FNDG_YMD,APLY_YR,LAST_MDFCN_DT,BSC_PLAN_NM,DST_RSK_DSTRCT_GRD_CD,SUBLOTNO,MAO_CD,MNG_CTZN_JBGD_NM
0,1.138010e+09,NaN,붕괴,국립공원,NaN,1138000000,4-350 외 3필지,NaN,1.138010e+24,1944.0,...,0.0,NaN,NaN,NaN,2024/06/07 09:24:50.000000000,NaN,3.0,0.0,NaN,NaN
1,1.165010e+09,NaN,NaN,지방1급하천,NaN,1165000000,NaN,NaN,NaN,26000.0,...,0.0,NaN,NaN,NaN,2022/12/05 22:04:59.000000000,NaN,1.0,2.0,NaN,방배2동
2,1.165011e+09,NaN,NaN,지방도,NaN,1165000000,NaN,NaN,NaN,45000.0,...,0.0,NaN,NaN,2006.0,2022/12/05 22:05:44.000000000,NaN,1.0,NaN,NaN,서초2동
3,1.165010e+09,NaN,산사태,사유림,NaN,1165000000,NaN,NaN,NaN,4126000.0,...,0.0,NaN,NaN,NaN,2023/03/04 14:40:54.000000000,NaN,1.0,1.0,NaN,NaN
4,1.165010e+09,NaN,NaN,사유림,NaN,1165000000,일대,NaN,NaN,258000.0,...,0.0,일대,NaN,NaN,2023/03/04 14:41:08.000000000,NaN,1.0,16.0,NaN,NaN

In [672]:
# import os
# import requests
# import pandas as pd
# from pathlib import Path
# from dotenv import load_dotenv

# load_dotenv()

# BASE_URL = "https://www.safetydata.go.kr/V2/api/DSSP-IF-00117"
# SERVICE_KEY = os.getenv("FLOODING_API")

# # ✅ ipynb용 저장 경로
# PROJECT_ROOT = Path.cwd()
# OUTPUT_PATH = PROJECT_ROOT / "data" / "raw" / "DSSP_IF_00117_all.csv"


# def _parse_response(payload: dict):
#     """
#     API 응답 JSON에서 데이터(body)와 전체 개수(totalCount) 추출
#     - 마지막 페이지 이후에는 body=None이 올 수 있어 -> []로 처리
#     """
#     items = payload.get("body")
#     total_cnt = payload.get("totalCount")

#     if items is None:
#         items = []  # ✅ 정상 종료용

#     return items, total_cnt


# def fetch_data(page_no=1, num_of_rows=1000):
#     """
#     DSSP-IF-00117 한 페이지 수집
#     Returns: (df, total_cnt)
#     """
#     if not SERVICE_KEY:
#         raise ValueError("[CRAWL_00117] FLOODING_API 환경변수(.env) 설정 필요")

#     params = {
#         "serviceKey": SERVICE_KEY,
#         "returnType": "json",
#         "pageNo": page_no,
#         "numOfRows": num_of_rows,
#     }

#     try:
#         res = requests.get(BASE_URL, params=params, timeout=30)
#         res.raise_for_status()
#         payload = res.json()
#     except requests.exceptions.RequestException as e:
#         raise RuntimeError(f"[CRAWL_00117] API 호출 오류: {e}")
#     except ValueError as e:
#         raise RuntimeError(f"[CRAWL_00117] JSON 파싱 오류: {e}")

#     # ✅ API 헤더 결과 코드 체크 (실패면 바로 원인 표시)
#     header = payload.get("header", {})
#     if str(header.get("resultCode")) not in ("00", "0", "None"):
#         raise RuntimeError(
#             f"[CRAWL_00117] API Error {header.get('resultCode')}: "
#             f"{header.get('resultMsg')} / {header.get('errorMsg')}"
#         )

#     items, total_cnt = _parse_response(payload)
#     return pd.DataFrame(items), total_cnt


# def save_data(output_path=OUTPUT_PATH, max_rows=None):
#     """
#     DSSP-IF-00117 전체 수집 후 CSV 저장
#     """
#     path = Path(output_path)
#     path.parent.mkdir(parents=True, exist_ok=True)

#     print(f"[CRAWL_00117] 데이터 수집 시작: {path}")

#     ROWS_PER_PAGE = 1000

#     df_init, total_cnt = fetch_data(page_no=1, num_of_rows=ROWS_PER_PAGE)
#     all_dfs = [df_init]

#     if total_cnt is None:
#         print("[CRAWL_00117] totalCount가 없어 1페이지만 저장합니다.")
#     else:
#         total_cnt = int(total_cnt)
#         print(f"[CRAWL_00117] 전체 데이터 수: {total_cnt}")

#         total_pages = (total_cnt + ROWS_PER_PAGE - 1) // ROWS_PER_PAGE

#         for page_no in range(2, total_pages + 1):
#             df_page, _ = fetch_data(page_no=page_no, num_of_rows=ROWS_PER_PAGE)

#             # ✅ 마지막 페이지 이후 body=None -> df_page empty면 정상 종료
#             if df_page.empty:
#                 break

#             all_dfs.append(df_page)

#             current_total = sum(len(d) for d in all_dfs)
#             print(f"[CRAWL_00117] 페이지 {page_no}/{total_pages} 수집 완료 (누적: {current_total}개)")

#             if max_rows and current_total >= max_rows:
#                 break

#     df_flooding = pd.concat(all_dfs, ignore_index=True)

#     if max_rows:
#         df_flooding = df_flooding.head(max_rows)

#     df_flooding.to_csv(path, index=False, encoding="utf-8-sig")
#     print(f"[CRAWL_00117] 데이터 수집 완료: {path} (총 {len(df_flooding)}건)")

#     return df_flooding


# # ✅ ipynb에서는 아래 한 줄 실행하면 됨
# df_flooding = save_data()
# df_flooding.head()

In [673]:
df_flooding = pd.read_csv('../../../data/raw/DSSP_IF_00117_all.csv')
df_flooding.head()

,FLDN_GRD,FLDN_DOWA,FLDN_END_YMD,FLDN_YR,FLDN_CS_DTL_NM,FLDN_BGNG_YMD,STDG_SGG_CD,FLDN_END_TM,FLDN_AREA,STDG_CTPV_CD,FLDN_DST_NM,SN,GEOM,FLDN_BGNG_TM
0,3,1.24,20020901,2002,"농경지 침수 및 농작물 피해, 하우스 파손",20020831,47130,0.0,541340.0,47,2002년도 제 15호태풍 루사 집중호우,118,"POLYGON((14391405.9522219 4297942.3250228399,1...",1600.0
1,3,1.28,20020901,2002,"농경지 침수 및 농작물 피해, 하우스 파손",20020831,47130,0.0,421755.0,47,2002년도 제 15호태풍 루사 집중호우,175,POLYGON((14391758.689776201 4300188.5026681097...,1600.0
2,2,0.75,20020901,2002,"농경지 침수 및 농작물 피해, 하우스 파손",20020831,47130,0.0,140736.0,47,2002년도 제 15호태풍 루사 집중호우,98,"POLYGON((14391054.734821901 4298867.38571792,1...",1600.0
3,1,0.31,20020901,2002,"농경지 침수 및 농작물 피해, 하우스 파손",20020831,47130,0.0,421755.0,47,2002년도 제 15호태풍 루사 집중호우,52,"POLYGON((14391777.3056948 4300437.8760203598,1...",1600.0
4,5,2.15,20020901,2002,"농경지 침수 및 농작물 피해, 하우스 파손",20020831,47130,0.0,541340.0,47,2002년도 제 15호태풍 루사 집중호우,91,POLYGON((14391994.174304301 4298291.6817322299...,1600.0

In [674]:
df_disaster.head(15)

,STDG_CD,CNTNC_VL,DST_RSK_DSTRCTCD,FCLTY_GRD_NM,DCSD_CNT,DST_RSK_DSTRCT_RGN_CD,DST_RSK_DSTRCT_HONU,ACT_LMT_MUOR_SPTR,ROAD_NM_CD,DSGN_AREA,...,APLY_YN,DADDR,FNDG_YMD,APLY_YR,LAST_MDFCN_DT,BSC_PLAN_NM,DST_RSK_DSTRCT_GRD_CD,SUBLOTNO,MAO_CD,MNG_CTZN_JBGD_NM
0,1.138010e+09,NaN,붕괴,국립공원,NaN,1138000000,4-350 외 3필지,NaN,1.138010e+24,1944.0,...,0.0,NaN,NaN,NaN,2024/06/07 09:24:50.000000000,NaN,3.0,0.0,NaN,NaN
1,1.165010e+09,NaN,NaN,지방1급하천,NaN,1165000000,NaN,NaN,NaN,26000.0,...,0.0,NaN,NaN,NaN,2022/12/05 22:04:59.000000000,NaN,1.0,2.0,NaN,방배2동
2,1.165011e+09,NaN,NaN,지방도,NaN,1165000000,NaN,NaN,NaN,45000.0,...,0.0,NaN,NaN,2006.0,2022/12/05 22:05:44.000000000,NaN,1.0,NaN,NaN,서초2동
3,1.165010e+09,NaN,산사태,사유림,NaN,1165000000,NaN,NaN,NaN,4126000.0,...,0.0,NaN,NaN,NaN,2023/03/04 14:40:54.000000000,NaN,1.0,1.0,NaN,NaN
4,1.165010e+09,NaN,NaN,사유림,NaN,1165000000,일대,NaN,NaN,258000.0,...,0.0,일대,NaN,NaN,2023/03/04 14:41:08.000000000,NaN,1.0,16.0,NaN,NaN
5,1.150011e+09,NaN,공사완료,지방관리,NaN,1150000000,1120번지,NaN,NaN,5000000.0,...,0.0,NaN,NaN,NaN,2022/10/25 09:30:40.000000000,NaN,2.0,NaN,NaN,공항동1107(25통장)
6,1.150011e+09,NaN,공사완료,지방관리,NaN,1150000000,616,NaN,NaN,1.0,...,0.0,NaN,NaN,NaN,2022/10/25 09:31:34.000000000,NaN,2.0,NaN,NaN,방화동645-32(5통장)
7,1.150011e+09,NaN,NaN,지방1급하천,0.0,1150000000,NaN,0.0,NaN,850000.0,...,0.0,600-1 일원,NaN,NaN,2022/12/05 22:04:12.000000000,NaN,3.0,1.0,NaN,방화2동 동대표
8,1.150010e+09,NaN,NaN,국가하천,0.0,1150000000,화곡동 1106-1 일원,0.0,NaN,110720.0,...,0.0,화곡동 1106-1 일원,NaN,2011.0,2024/10/30 13:35:58.000000000,NaN,1.0,1.0,NaN,자율방재단 동대표
9,1.150010e+09,NaN,NaN,국가하천,0.0,1150000000,화곡동 949-4 일원,0.0,NaN,96667.0,...,0.0,화곡동 949-4 일원,NaN,NaN,2023/01/04 13:27:31.000000000,NaN,1.0,4.0,NaN,자율방재단 화곡1
10,2.614012e+09,NaN,NaN,지방관리,0.0,2614068000,NaN,0.0,NaN,654.0,...,0.0,NaN,NaN,NaN,2017/03/02 12:25:33.000000000,NaN,2.0,1.0,4.0,암남동 12통장
11,2.614012e+09,NaN,급경사 암반,지방관리,NaN,2614065000,남부민초등학교 일원,NaN,NaN,NaN,...,NaN,남부민초등학교 일원,NaN,NaN,2013/06/13 12:06:31.000000000,NaN,3.0,6.0,1.0,NaN
12,2.623010e+09,NaN,NaN,지방관리,NaN,2623052000,성서초등학교 일원,NaN,NaN,NaN,...,NaN,성서초등학교 일원,NaN,NaN,2012/03/29 10:16:50.000000000,NaN,1.0,6.0,1.0,통장
13,5.172025e+09,NaN,NaN,지방관리,0.0,5172025000,NaN,2.0,NaN,130826.0,...,0.0,NaN,20121012.0,2010.0,2022/05/02 17:57:45.000000000,홍천군풍수해저감종합계획,1.0,NaN,NaN,결운2리장
14,5.172039e+09,5.0,NaN,지방2급하천,0.0,5172039000,NaN,2.0,NaN,60000.0,...,0.0,NaN,20121012.0,2010.0,2022/05/02 17:57:40.000000000,홍천군 풍수해저감종합계획,1.0,NaN,NaN,광원2리장

In [675]:
df_flooding['FLDN_BGNG_YMD'] = pd.to_numeric(
    df_flooding['FLDN_BGNG_YMD'].astype(str).str[-4:-2],
    errors='coerce'
).astype('Int64')

In [676]:
df_flooding['FLDN_BGNG_YMD']

0        8
1        8
2        8
3        8
4        8
        ..
37998    7
37999    7
38000    7
38001    7
38002    7
Name: FLDN_BGNG_YMD, Length: 38003, dtype: Int64

In [677]:
df_flooding = df_flooding.dropna(subset =['FLDN_BGNG_YMD']).copy()

In [678]:
df_flooding['FLDN_BGNG_YMD'].isnull().sum()

np.int64(0)

In [679]:
df_flooding[['FLDN_GRD']] # 살릴 컬럼

       FLDN_GRD
0             3
1             3
2             2
3             1
4             5
...         ...
37998         3
37999         3
38000         3
38001         3
38002         1

[37062 rows x 1 columns]

In [680]:
import pandas as pd
print(type(df_disaster))

<class 'pandas.DataFrame'>

In [681]:
df_disaster = df_disaster.dropna(subset = ['STDG_CD']).copy()

In [682]:
df_disaster['STDG_CD'] = df_disaster['STDG_CD'].astype(str).str[:5].astype(int)

In [683]:
df_disaster = df_disaster.dropna(subset = ['DSGN_YMD']).copy()

In [684]:
df_disaster['DSGN_YMD'] = df_disaster['DSGN_YMD'].astype(str).str[:4].astype(int)

In [685]:
df_disaster = df_disaster[df_disaster['DSGN_YMD'] >= 2016].copy()

df_disaster 필요한 컬럼들만 남겨놨고, df_flooding이랑 연결할 STDG_CD는 앞 다섯숫자만 남겨둠

In [686]:
df_disaster_processing = df_disaster[['DSGN_YMD','DAM_DAY_RNFL','INJPSN_CNT','STDG_CD']]

In [687]:
df_disaster.head()

,STDG_CD,CNTNC_VL,DST_RSK_DSTRCTCD,FCLTY_GRD_NM,DCSD_CNT,DST_RSK_DSTRCT_RGN_CD,DST_RSK_DSTRCT_HONU,ACT_LMT_MUOR_SPTR,ROAD_NM_CD,DSGN_AREA,...,APLY_YN,DADDR,FNDG_YMD,APLY_YR,LAST_MDFCN_DT,BSC_PLAN_NM,DST_RSK_DSTRCT_GRD_CD,SUBLOTNO,MAO_CD,MNG_CTZN_JBGD_NM
42,41480,NaN,내수침수,지방관리,0.0,4148000000,NaN,2.0,NaN,279794.0,...,0.0,NaN,20240315.0,2003.0,2024/09/13 09:31:39.000000000,NaN,2.0,NaN,NaN,율곡2리 이장
138,52770,NaN,NaN,지방2급하천,0.0,5277000000,NaN,2.0,NaN,22100.0,...,0.0,NaN,19900101.0,2015.0,2022/10/31 12:22:49.000000000,오수천기본계획,3.0,0.0,NaN,현포마을이장
139,52770,5.0,NaN,지방1급하천,0.0,5277032000,NaN,2.0,NaN,55000.0,...,0.0,NaN,19900101.0,2016.0,2019/07/06 15:41:30.000000000,오수천기본계획,3.0,0.0,5.0,서호마을미장
140,52770,NaN,NaN,지방2급하천,0.0,5277037000,NaN,2.0,NaN,332100.0,...,0.0,NaN,20041001.0,2015.0,2021/11/24 15:35:14.000000000,금월천기본계획,3.0,0.0,NaN,대각마을이장
141,52770,NaN,NaN,지방2급하천,0.0,5200000000,NaN,2.0,NaN,71800.0,...,0.0,NaN,20010501.0,2016.0,2022/05/01 09:50:05.000000000,양지천기본계획,3.0,0.0,NaN,정산마을이장

In [688]:
df_flooding[['FLDN_GRD']]  # 침수 등급

       FLDN_GRD
0             3
1             3
2             2
3             1
4             5
...         ...
37998         3
37999         3
38000         3
38001         3
38002         1

[37062 rows x 1 columns]

In [689]:
df_flooding[['STDG_SGG_CD']]    # 법정동시군구코드

       STDG_SGG_CD
0            47130
1            47130
2            47130
3            47130
4            47130
...            ...
37998        48740
37999        48740
38000        48740
38001        48740
38002        48740

[37062 rows x 1 columns]

In [690]:
df_flooding[['FLDN_YR']] # 침수년도

      FLDN_YR
0        2002
1        2002
2        2002
3        2002
4        2002
...       ...
37998    2011
37999    2011
38000    2011
38001    2011
38002    2011

[37062 rows x 1 columns]

In [691]:
df_flooding = df_flooding.dropna(subset=['FLDN_YR']).copy()

In [692]:
df_flooding[['FLDN_YR']].dtypes # 확인한 결과 str 형식이라서 int로 바꿔줘야됨

FLDN_YR    str
dtype: object

In [693]:
df_flooding[df_flooding["FLDN_YR"].astype(str).str.contains("외", na=False)][["FLDN_YR"]].head(20)
# 특정 단어도 포함

Empty DataFrame
Columns: [FLDN_YR]
Index: []

In [694]:
s = pd.to_numeric(df_flooding['FLDN_YR'],errors='coerce')

In [695]:
df_flooding = df_flooding[s.notna()].copy()
df_flooding['FLDN_YR'] = s[s.notna()].astype(int)

In [696]:
df_flooding = df_flooding[df_flooding['FLDN_YR'] >= 2016].copy()

In [697]:
df_flooding_processing = df_flooding[['FLDN_YR','FLDN_GRD','STDG_SGG_CD','FLDN_BGNG_YMD']]

In [698]:
df_disaster_processing['STDG_CD'] = df_disaster_processing['STDG_CD'].astype('int')

In [699]:
df_flooding_processing['STDG_SGG_CD'] = df_flooding_processing['STDG_SGG_CD'].astype('int')

In [700]:
disaster = df_disaster_processing.rename(columns={'STDG_CD' : 'SIGUNGU','DSGN_YMD':'FLOOD_YEAR','DAM_DAY_RNFL':'DAM_RAIN','INJPSN_CNT':'DEAD'})
flooding = df_flooding_processing.rename(columns={'FLDN_YR':'FLOOD_YEAR','FLDN_GRD':'FLOOD_GRD','STDG_SGG_CD':'SIGUNGU','FLDN_BGNG_YMD':'FLOOD_MONTH'})

# df_merge = pd.merge(disaster, flooding, on=['FLOOD_YEAR','SIGUNGU'],how='inner')
# df_merge.shape

In [701]:
flooding

       FLOOD_YEAR  FLOOD_GRD  SIGUNGU  FLOOD_MONTH
433          2017          3    43111            7
518          2017          2    43111            7
524          2017          2    43111            7
525          2017          2    43111            7
526          2017          3    43111            7
...           ...        ...      ...          ...
36139        2021          5    46800            7
36140        2021          2    45730            8
36160        2021          2    45730            8
36219        2022          2    44790            8
36220        2022          2    44790            8

[25030 rows x 4 columns]

In [702]:
# df_merge.sort_values(by='FLOOD_YEAR').reset_index(drop=True)
disaster.sort_values(by='FLOOD_YEAR').reset_index()

     index  FLOOD_YEAR  DAM_RAIN  DEAD  SIGUNGU
0      138        2016     150.0   0.0    52770
1      190        2016     149.0   1.0    52710
2      186        2016     381.0   0.0    43770
3      189        2016     409.0   0.0    43720
4      185        2016       0.0   0.0    43800
..     ...         ...       ...   ...      ...
926   2645        2025      59.0   NaN    48860
927    455        2025       NaN   3.0    46840
928   2555        2026       NaN   NaN    43750
929   2554        2026       NaN   NaN    48240
930   2553        2026       NaN   NaN    48240

[931 rows x 5 columns]

In [703]:
df_merge = pd.merge(disaster, flooding, on=['FLOOD_YEAR','SIGUNGU'],how='left')
df_merge.head()

   FLOOD_YEAR  DAM_RAIN  DEAD  SIGUNGU  FLOOD_GRD  FLOOD_MONTH
0        2024     300.0   0.0    41480        NaN         <NA>
1        2016     150.0   0.0    52770        NaN         <NA>
2        2016     150.0   0.0    52770        NaN         <NA>
3        2016     150.0   0.0    52770        NaN         <NA>
4        2016     150.0   0.0    52770        NaN         <NA>

In [ ]:
df_merge.sort_values(by='FLOOD_YEAR')

      FLOOD_YEAR  DAM_RAIN  DEAD  SIGUNGU  FLOOD_GRD  FLOOD_MONTH
19          2016     149.0   1.0    52710        NaN         <NA>
1           2016     150.0   0.0    52770        NaN         <NA>
5227        2016     100.0   0.0    43740        NaN         <NA>
5263        2016     150.0   NaN    52770        NaN         <NA>
5273        2016       NaN   NaN    43760        NaN         <NA>
...          ...       ...   ...      ...        ...          ...
23          2025       0.0   0.0    47290        NaN         <NA>
9241        2025      59.0   NaN    48860        NaN         <NA>
8936        2026       NaN   NaN    43750        NaN         <NA>
8934        2026       NaN   NaN    48240        NaN         <NA>
8935        2026       NaN   NaN    48240        NaN         <NA>

[9259 rows x 6 columns]

In [705]:
df_merge['FLOOD_MONTH'].isnull().sum()

np.int64(821)

In [706]:
# df_merge.to_csv("../../../data/processed/Flooding_Disaster.csv",index=False, encoding="utf-8")

In [707]:
df_merge[['DEAD']].isnull().sum()

DEAD    8702
dtype: int64

In [708]:
df_merge[['DEAD']]= df_merge[['DEAD']].fillna(0)

In [709]:
rain_median = df_merge['DAM_RAIN'].median()

In [710]:
df_merge[['DAM_RAIN']] = df_merge[['DAM_RAIN']].fillna(rain_median)

In [711]:
df_merge[['DAM_RAIN']]

      DAM_RAIN
0        300.0
1        150.0
2        150.0
3        150.0
4        150.0
...        ...
9254     198.0
9255     198.0
9256     200.0
9257     198.0
9258       0.0

[9259 rows x 1 columns]

In [712]:
df_merge['FLOOD_GRD'].value_counts()

FLOOD_GRD
2.0    3900
3.0    1564
1.0    1426
5.0     870
6.0     597
4.0      81
Name: count, dtype: int64

In [713]:
flood_grade_mean = df_merge['FLOOD_GRD']
df_merge[['FLOOD_GRD']] = df_merge[['FLOOD_GRD']].fillna(2)

In [714]:
df_merge[['FLOOD_GRD']]

      FLOOD_GRD
0           2.0
1           2.0
2           2.0
3           2.0
4           2.0
...         ...
9254        2.0
9255        2.0
9256        2.0
9257        2.0
9258        2.0

[9259 rows x 1 columns]

In [715]:
df_merge['FLOOD_GRD'].value_counts()

FLOOD_GRD
2.0    4721
3.0    1564
1.0    1426
5.0     870
6.0     597
4.0      81
Name: count, dtype: int64

In [716]:
df_merge

      FLOOD_YEAR  DAM_RAIN  DEAD  SIGUNGU  FLOOD_GRD  FLOOD_MONTH
0           2024     300.0   0.0    41480        2.0         <NA>
1           2016     150.0   0.0    52770        2.0         <NA>
2           2016     150.0   0.0    52770        2.0         <NA>
3           2016     150.0   0.0    52770        2.0         <NA>
4           2016     150.0   0.0    52770        2.0         <NA>
...          ...       ...   ...      ...        ...          ...
9254        2023     198.0   0.0    44760        2.0         <NA>
9255        2018     198.0   0.0    46840        2.0         <NA>
9256        2022     200.0   0.0    51730        2.0         <NA>
9257        2023     198.0   0.0    52210        2.0         <NA>
9258        2021       0.0   0.0    47770        2.0         <NA>

[9259 rows x 6 columns]

In [717]:
df_merge = df_merge.dropna(subset=['FLOOD_MONTH'])

In [718]:
df_merge

      FLOOD_YEAR  DAM_RAIN  DEAD  SIGUNGU  FLOOD_GRD  FLOOD_MONTH
11          2021       0.0   0.0    43800        1.0            8
12          2021       0.0   0.0    43800        1.0            8
13          2021       0.0   0.0    43800        1.0            8
49          2020     198.0   0.0    43130        2.0            7
50          2020     198.0   0.0    43130        3.0            8
...          ...       ...   ...      ...        ...          ...
9209        2021     198.0   0.0    46170        2.0            7
9210        2021     198.0   0.0    46170        1.0            7
9211        2021     198.0   0.0    46170        3.0            7
9212        2021     198.0   0.0    46170        1.0            7
9213        2021     198.0   0.0    46170        1.0            7

[8438 rows x 6 columns]

In [719]:
df_merge.to_csv("../../../data/processed/Flooding_Disaster.csv",index=False, encoding="utf-8")